config/routes.rb
Suitefolio::Application.routes.draw do

  resources :collaborates


  mount RailsAdmin::Engine => '/cortana', :as => 'rails_admin'

  devise_for :admins

  devise_for :users
  
  resources :users do
    member do
      get :following, :followers, :resume, :blog, :snips, :messages
    end
    resources :messages, only: [:create]
    resources :offers, only: [:new, :create]
    resources :tags, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy, :show]
  resources :offers, only: [:show]
  resources :tags, only: [:show, :create, :destroy]
  resources :messages, only: [:index, :destroy]
  
  resources :jobs do
    resources :tags, only: [:create, :destroy]
    member do
      resources :applications, only: [:new, :create]
    end
  end
  
  resources :snips, only: [:new, :destroy, :show] do
    member do
      get :like, :likes, :unlike
    end
    resources :comments, only: [:create, :new]
  end
  
  resources :images, only: [:create, :edit, :update]
  resources :videos, only: [:create, :edit, :update]
  resources :websites, only: [:create, :edit, :update]
  
  resources :resumes, only: [:destroy, :new]
  resources :employments, only: [:create, :edit, :update]
  
  resources :likes, only: [:show]
  resources :notifications, only: [:index]
  resources :blogs
  
  resources :comments, only: [:new, :create, :destroy, :show]
  resources :apps, :controller => :applications
  resources :applications, only: :show
  
  get '/search', to: 'search#search'
  get '/search/users/', to: 'search#users'
  get '/search/jobs/', to: 'search#jobs'

  match ':id' => 'users#show', :via => :get, :as => :id
  
  root :to => "welcome#index"
end

app/models/snip.rb
class Snip < ActiveRecord::Base
  attr_accessible :user_id, :name, :desc
  belongs_to :snip, :polymorphic => true
  belongs_to :user
  has_many :likes
  has_many :comments
  validates :user_id, presence: true
  validates :name, presence: true
  default_scope :order => "id DESC"
  
end

app/controllers/snips_controller.rb
class SnipsController < ApplicationController
  before_filter :authenticate_user!
  include SnipsHelper
  
  def update
    @snip = Snip.find(params[:id])
    @snip.update_attributes(params[:snip])
  end

  def destroy
    @snip = Snip.find(params[:id])
    @snip.destroy
    respond_to do |format|
      format.html { redirect_to current_user }
      format.js
    end
  end
  
  def show
    @snip = Snip.find(params[:id])
    @snip.comments.each do |comment|
      @notification = Notification.where(:user_id => current_user.id, :notify_id => comment.id, :notify_type => 'Comment').first
      @notification.update_attributes(:read => true) if @notification
    end
  end
  
  def like 
    @snip = Snip.find(params[:id])
    @like = @snip.likes.build(:user_id => current_user.id)
    respond_to do |format|
      format.html { redirect_to @snip } if @like.save
      format.js if @like.save
    end
  end
  
  def unlike
    @snip = Snip.find(params[:id])
    @like = @snip.likes.find_by_user_id(current_user.id)
    @like.destroy
    respond_to do |format|
      format.html { redirect_to @snip }
      format.js
    end
  end
end

app/helpers/snips_helper.rb
module SnipsHelper  
  def composer
    @snip = Snip.new
    @image = Image.new
    @video = Video.new
    @website = Website.new
  end
end

app/views/snips/_form.html.erb
<ul class="nav nav-tabs">
	<li class="active"><a href="#image" data-toggle="tab">Photo</a></li>
	<li><a href="#video" data-toggle="tab">Video</a></li>
	<li><a href="#website" data-toggle="tab">Website</a></li>
</ul>
<div class="boxshadow"></div>
<div class="box">
	<div class="tab-content">
		
		<div class="tab-pane active" id="image">
			<%= render 'images/form' %>
		</div>
		<div class="tab-pane" id="video">
			<%= render 'videos/form' %>
		</div>
		<div class="tab-pane" id="website">
			<%= render 'websites/form' %>
		</div>
		
	</div>
</div>

app/views/snips/_like.html.erb
<% if snip.likes.find_by_user_id(current_user.id).present? %>
<%= link_to([:unlike, snip], :remote => true, :class => 'btn btn-tiny disabled') do %>
<i class="icon-thumbs-up"></i>
<% end %>
<% else %>
<%= link_to([:like, snip], :remote => true, :class => 'btn btn-tiny') do %>
<i class="icon-thumbs-up"></i>
<% end %>
<% end %>
<%= link_to [:likes, snip], :class => 'btn btn-tiny' do %>
<span class="like-count"><%= snip.likes.count %></span>
<% end %>

app/views/snips/_snip.html.erb
<li class="span6" data-id="<%= snip.id %>">
	<div class="thumbnail">
	<%= link_to "Delete", snip_path(snip), method: :delete, :remote => true, :class => 'delete' if current_user?(snip.user) %>
	<%= render snip.snip %>
	<div class="caption clearfix">
		<h2><%= link_to snip.name, snip %></h2>
		<div class="btn-group like-group">
			<%= render 'snips/like', :snip => snip %>
			<%= link_to snip, :class => 'btn btn-tiny' do %>
			<i class="icon-inbox"></i>
			<% end %>
			<%= link_to snip, :class => 'btn btn-tiny' do %>
			<%= snip.comments.count %>
			<% end %>
		</div>
	</div>
</li>

app/views/snips/_snips.html.erb
<% if @snips.any? %>
<div class="snip">
	<div class="thumbnails">
		<ul>
		<%= render @snips %>
		</ul>
		<div class="span12">
			<%= will_paginate @snips %>
		</div>
	</div>
</div>
<% else %>
<%= render 'shared/empty', :title => @user.name + ' has not uploaded anything yet.', :caption => 'Check back soon.' %>
<% end %>

app/views/snips/destroy.js.erb
$snip = $('[data-id=<%= @snip.id %>]');
$snip.remove();

app/views/snips/like.js.erb
$snip = $('[data-id=<%= @snip.id %>]');
$likes = $snip.find('.like-group');
$likes.html('<%= escape_javascript(render 'snips/like', :snip => @snip) %>');

app/views/snips/show.html.erb
<% if current_user?(@user) %>
	<%= link_to "Edit", [:edit, @snip.snip], :class => 'btn pull-right' %><Br /><br />
<% end %>
<div id="snip">
	<div class="stage">
		<div class="info">
			<label class="title"><%= @snip.name %> <small><%= @snip.snip.canonical %></small></label>
			<% if @snip.snip.is_a? Website %>
			<label class="title"><%= link_to "view web site", @snip.snip.url %></label>
			<% end %>
			<label class="date">added <%= time_ago_in_words(@snip.created_at) %> ago by <%= link_to @snip.user.name, @snip.user %></label>
		</div>
		<% if @snip.snip.is_a? Video %>
			<iframe src="http://player.vimeo.com/video/<%= @snip.snip.vimeo %>" frameborder="0" 
				webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
		<% else %>
			<%= image_tag @snip.snip.image.url(:large) %>
		<% end %>
	</div>
	<div class="content">
		<div class="head small smaller black">
			<h2><i class="icon icon-pencil"></i> Comments</h2>
		</div>
		<div id="comment">
		<%= render 'comments/comments', :collection => @snip.comments %>
		</div>
	</div>
</div>

app/views/snips/unlike.html.erb
$snip = $('[data-id=<%= @snip.id %>]');
$likes = $snip.find('.like-group');
$likes.html('<%= escape_javascript(render 'snips/like', :snip => @snip) %>');