config/routes.rb
Suitefolio::Application.routes.draw do

  resources :collaborates


  mount RailsAdmin::Engine => '/cortana', :as => 'rails_admin'

  devise_for :admins

  devise_for :users
  
  resources :users do
    member do
      get :following, :followers, :resume, :blog, :snips, :messages
    end
    resources :messages, only: [:create]
    resources :offers, only: [:new, :create]
    resources :tags, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy, :show]
  resources :offers, only: [:show]
  resources :tags, only: [:show, :create, :destroy]
  resources :messages, only: [:index, :destroy]
  
  resources :jobs do
    resources :tags, only: [:create, :destroy]
    member do
      resources :applications, only: [:new, :create]
    end
  end
  
  resources :snips, only: [:new, :destroy, :show] do
    member do
      get :like, :likes, :unlike
    end
    resources :comments, only: [:create, :new]
  end
  
  resources :images, only: [:create, :edit, :update]
  resources :videos, only: [:create, :edit, :update]
  resources :websites, only: [:create, :edit, :update]
  
  resources :resumes, only: [:destroy, :new]
  resources :employments, only: [:create, :edit, :update]
  
  resources :likes, only: [:show]
  resources :notifications, only: [:index]
  resources :blogs
  
  resources :comments, only: [:new, :create, :destroy, :show]
  resources :apps, :controller => :applications
  resources :applications, only: :show
  
  get '/search', to: 'search#search'
  get '/search/users/', to: 'search#users'
  get '/search/jobs/', to: 'search#jobs'

  match ':id' => 'users#show', :via => :get, :as => :id
  
  root :to => "welcome#index"
end

app/models/employment.rb
class Employment < ActiveRecord::Base
  has_one :resume, :as => :resume
  validates :resume, presence: true
  accepts_nested_attributes_for :resume
  attr_accessible :desc, :employer, :position, :snip
  validates :employer, presence: true
  validates :position, presence: true
  validates :desc, presence: true
  
  def canonical
    "job"
  end
  
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  before_filter :authenticate_user!
  
  def create
    @employment = Employment.new(params[:employment])
    @resume = current_user.resumes.build(params[:resume])
    @employment.resume = @resume
    if @employment.save
      redirect_to current_user
    else
      render 'new'
    end
  end
  
  def edit
    @employment = Employment.find(params[:id])
    @resume = @employment.resume
  end
  
  def update
    @employment = Employment.find(params[:id])
    @resume = @employment.resume
    @employment.update_attributes(params[:employment])
    @resume.update_attributes(params[:resume])
    redirect_to resume_user_path(current_user)
  end
  
end

app/views/employments/_employment.html.erb
<%= link_to "Edit", edit_employment_path(employment), class: "btn pull-right" if current_user?(employment.resume.user) %>
<h2><%= employment.position %></h2>
<h3><%= employment.employer %></h3>
<p><%= employment.desc %></p>

app/views/employments/_form.html.erb
<div class="form-horizontal">
<%= form_for(@employment) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="control-group">
		<%= f.label :employer, :class => 'control-label' %>
		<div class="controls">
			<%= f.text_field :employer %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :position, :class => 'control-label' %>
		<div class="controls">
			<%= f.text_field :position %>
		</div>
	</div>
	<%= fields_for @resume do |r| %>
	<div class="control-group">
		<%= r.label :time_start, 'From', :class => 'control-label' %>
		<div class="controls">
			<%= r.date_select :time_start, :order => [:month, :year] %>
		</div>
	</div>
	<div class="control-group">
		<%= r.label :time_end, 'To', :class => 'control-label' %>
		<div class="controls">
			<%= r.date_select :time_end, :order => [:month, :year] %>
			<label class="checkbox">
				<%= r.check_box :present %> I currently work here.
			</label>
		</div>
	</div>
	<% end %>
	<div class="control-group">
		<%= f.label :desc, :class => 'control-label' %>
		<div class="controls">
			<%= f.text_area :desc %>
		</div>
	</div>
	<div class="control-group">
		<div class="controls">
			<%= f.submit "Add", class: "btn btn-large btn-primary" %>
		</div>
	</div>
<% end %>	
</div>

app/views/employments/edit.html.erb
<div class="form large">
	<div class="head small">
		<h3><i class="icon icon-briefcase"></i> <%= @employment.position %></h3>
	</div>
	<div class="box">
		<%= render 'employments/form' %>
	</div>
</div>

app/views/employments/new.html.erb
<div class="form large">
	<div class="head small">
		<h3><i class="icon icon-briefcase"></i> Add</h3>
	</div>
	<div class="box">
		<%= render 'employments/form' %>
	</div>
</div>