config/routes.rb
Suitefolio::Application.routes.draw do

  resources :collaborates


  mount RailsAdmin::Engine => '/cortana', :as => 'rails_admin'

  devise_for :admins

  devise_for :users
  
  resources :users do
    member do
      get :following, :followers, :resume, :blog, :snips, :messages
    end
    resources :messages, only: [:create]
    resources :offers, only: [:new, :create]
    resources :tags, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy, :show]
  resources :offers, only: [:show]
  resources :tags, only: [:show, :create, :destroy]
  resources :messages, only: [:index, :destroy]
  
  resources :jobs do
    resources :tags, only: [:create, :destroy]
    member do
      resources :applications, only: [:new, :create]
    end
  end
  
  resources :snips, only: [:new, :destroy, :show] do
    member do
      get :like, :likes, :unlike
    end
    resources :comments, only: [:create, :new]
  end
  
  resources :images, only: [:create, :edit, :update]
  resources :videos, only: [:create, :edit, :update]
  resources :websites, only: [:create, :edit, :update]
  
  resources :resumes, only: [:destroy, :new]
  resources :employments, only: [:create, :edit, :update]
  
  resources :likes, only: [:show]
  resources :notifications, only: [:index]
  resources :blogs
  
  resources :comments, only: [:new, :create, :destroy, :show]
  resources :apps, :controller => :applications
  resources :applications, only: :show
  
  get '/search', to: 'search#search'
  get '/search/users/', to: 'search#users'
  get '/search/jobs/', to: 'search#jobs'

  match ':id' => 'users#show', :via => :get, :as => :id
  
  root :to => "welcome#index"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @users = User.search params[:q]
    #@jobs = Job.search params[:q]
  end
  
  def users
    @users = User.search params[:q]
  end
  
  def jobs
    #@jobs = Job.search params[:q]
  end
end

app/views/search/_header.html.erb
<div class="head small">
	<h3 class="pull-left">
		<i class="icon icon-search"></i> <%= params[:q] %>
	</h3>
	<div class="btn-group pull-right">
		<%= link_to 'People', search_users_path(:q => params[:q]), :class => current_page?(search_users_path(:q => params[:q])) ? "btn active" : "btn" %>
		<%#= link_to 'Jobs', search_jobs_path(:q => params[:q]), :class => current_page?(search_jobs_path(:q => params[:q])) ? "btn active" : "btn" %>
	</div>
</div>

app/views/search/_results_jobs.html.erb
<div class="box">
	<div class="row">
		<h3 class="span12">
			<i class="icon icon-briefcase"></i> Jobs
		</h3>
		<% if @jobs.any? %>
		<%= render 'jobs/jobs', :collection => @jobs %>
		<% else %>
		<%= render 'shared/empty', :title => 'No results.', :caption => nil %>
		<% end %>
	</div>
</div>

app/views/search/_results_users.html.erb
<div class="box">
	<div class="row">
		<h3 class="span12">
			<i class="icon icon-user"></i> People
		</h3>
		<% if @users.any? %>
		<%= render 'users/users' %>
		<% else %>
		<%= render 'shared/empty', :title => 'No results.', :caption => nil %>
		<% end %>
	</div>
</div>

app/views/search/jobs.html.erb
<div class="content">
  <%= render 'header' %>
  <%= render 'results_jobs' %>
</div>

app/views/search/search.html.erb
<div class="content">
  <%= render 'header' %>
  <%= render 'results_users' %>
  <%#= render 'results_jobs' %>
</div>

app/views/search/users.html.erb
<div class="content">
  <%= render 'header' %>
  <%= render 'results_users' %>
</div>