config/routes.rb
Suitefolio::Application.routes.draw do

  resources :collaborates


  mount RailsAdmin::Engine => '/cortana', :as => 'rails_admin'

  devise_for :admins

  devise_for :users
  
  resources :users do
    member do
      get :following, :followers, :resume, :blog, :snips, :messages
    end
    resources :messages, only: [:create]
    resources :offers, only: [:new, :create]
    resources :tags, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy, :show]
  resources :offers, only: [:show]
  resources :tags, only: [:show, :create, :destroy]
  resources :messages, only: [:index, :destroy]
  
  resources :jobs do
    resources :tags, only: [:create, :destroy]
    member do
      resources :applications, only: [:new, :create]
    end
  end
  
  resources :snips, only: [:new, :destroy, :show] do
    member do
      get :like, :likes, :unlike
    end
    resources :comments, only: [:create, :new]
  end
  
  resources :images, only: [:create, :edit, :update]
  resources :videos, only: [:create, :edit, :update]
  resources :websites, only: [:create, :edit, :update]
  
  resources :resumes, only: [:destroy, :new]
  resources :employments, only: [:create, :edit, :update]
  
  resources :likes, only: [:show]
  resources :notifications, only: [:index]
  resources :blogs
  
  resources :comments, only: [:new, :create, :destroy, :show]
  resources :apps, :controller => :applications
  resources :applications, only: :show
  
  get '/search', to: 'search#search'
  get '/search/users/', to: 'search#users'
  get '/search/jobs/', to: 'search#jobs'

  match ':id' => 'users#show', :via => :get, :as => :id
  
  root :to => "welcome#index"
end

app/views/shared/_empty.html.erb
<div class="empty">
	<h1><%= title %></h1>
	<h2><%= caption %></h2>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form_blog.html.erb
<div class="span6 offset3">
  <%= form_for(@blog) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
    	<%= f.label :title %>
    	<%= f.text_field :title %>

    	<%= f.label :content %>
    	<%= f.text_area :content %>

    	<%= f.submit "Post", class: "btn btn-large btn-success" %>
  <% end %>
</div>

app/views/shared/_form_job.html.erb
  <%= form_for(@job) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
    	<%= f.text_field :position, placeholder: 'Position' %>

    	<%= f.text_area :description, placeholder: 'Description' %>
		
		<%= text_field :tags, :tags, :placeholder => "Add tags (separated by commas)" if @job.new_record? %>
		
		
    	<%= f.submit :class => "btn btn-large btn-primary" %>
  <% end %>
<div class="formtags"><%= render 'shared/form_tag', :object => @job, :tag => @tag unless @job.new_record? %></div>
<%= render 'tags/tags', :object => @job unless @job.new_record? %>


	

app/views/shared/_form_tag.html.erb
<%= form_for [object, tag], remote: true do |f| %>
	<%= f.text_field :tag, placeholder: 'Enter a skill...' %>
<% end %>

app/views/shared/_search.html.erb
<%= form_tag search_path, :method => :get do %>
	<%= text_field_tag :q, params[:q], placeholder: 'Search...' %>
<% end %>

app/views/shared/_user_info.html.erb
<div class="head small user">
	<div class="picture">
		<span>
			<%= image_tag @user.picture.url(:small) if @user.picture %>
			<span id="relationship" data-user="<%= @user.id %>">
				<%= link_to 'Edit', edit_user_path(current_user), :class => 'btn btn-tiny btn-primary' if current_user?(@user) %>
				<%= render 'users/relationship', :user => @user unless current_user?(@user) %>
			</span>
		</span>
	</div>
	<div class="name">
		<h2><%= @user.username %></h2>
		<h3><%= @user.name %></h3>
		<p><%= @user.location %></p>
		<%= render 'tags/tags', :object => @user %>
	</div>
	<div class="relationships">
		<div class="btn-group">
			<%= link_to following_user_path(@user), :id => 'following', :class => 'btn btn-small' do %>
			<%= @user.followed_users.count %>
			<% end %>
			<%= link_to following_user_path(@user), :class => 'btn btn-small' do %>
			Following
			<% end %>
		</div>
		<div class="btn-group">
		<%= link_to followers_user_path(@user), :id => 'followers', :class => 'btn btn-small' do %>
		<%= @user.followers.count %>
		<% end %>
			<%= link_to followers_user_path(@user), :class => 'btn btn-small' do %>
			Followers
			<% end %>
		</div>
		<% unless current_user?(@user) %>
		<div class="btn-group">
			<%#= link_to 'Offer', new_user_offer_path(@user), :class => 'btn btn-small' %>
			<%= link_to 'Message', user_messages_path(@user), :class => 'btn btn-small' %>
			<%= link_to 'Collaborate', "#", :class => 'btn btn-small' %>
		</div>
		<% end %>
	</div>
</div>